openapi: 3.0.3
info:
  title: ViajaJunto API
  description: Contrato da API do projeto ViajaJunto
  version: 1.0.0
paths:
  /api/v1/status:
    get:
      summary: Retorna o status da API
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP