name: Lint OpenAPI Contract

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  spectral:
    name: Run Spectral Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Spectral Lint
        uses: stoplightio/spectral-action@v1.4.0
        with:
          file_globs: 'docs/openapi.yaml'